// Stub for @solana/kit — Privy/x402 import these but we only use EVM
const noop = () => {};
const noopAsync = async () => {};
const noopReturn = () => noop;
const identity = (x) => x;

export const address = noop;
export const appendTransactionMessageInstruction = identity;
export const appendTransactionMessageInstructions = identity;
export const assertIsInstructionWithAccounts = noop;
export const assertIsInstructionWithData = noop;
export const assertIsTransactionMessageWithBlockhashLifetime = noop;
export const blockhash = noop;
export const compileTransaction = noop;
export const createKeyPairSignerFromBytes = noopAsync;
export const createKeyPairSignerFromPrivateKeyBytes = noopAsync;
export const createSolanaRpc = noopReturn;
export const createSolanaRpcSubscriptions = noopReturn;
export const createTransactionMessage = noopReturn;
export const decompileTransactionMessage = noop;
export const decompileTransactionMessageFetchingLookupTables = noopAsync;
export const devnet = noop;
export const fetchAddressesForLookupTables = noopAsync;
export const fetchEncodedAccounts = noopAsync;
export const getBase58Decoder = noopReturn;
export const getBase58Encoder = noopReturn;
export const getBase64Decoder = noopReturn;
export const getBase64Encoder = noopReturn;
export const getBase64EncodedWireTransaction = noop;
export const getCompiledTransactionMessageDecoder = noopReturn;
export const getSignatureFromTransaction = noop;
export const getTransactionDecoder = noopReturn;
export const getTransactionEncoder = noopReturn;
export const isSolanaError = () => false;
export const isTransactionModifyingSigner = () => false;
export const isTransactionPartialSigner = () => false;
export const isTransactionSigner = () => false;
export const mainnet = noop;
export const partiallySignTransactionMessageWithSigners = noopAsync;
export const pipe = (...fns) => (x) => fns.reduce((v, f) => typeof f === 'function' ? f(v) : v, x);
export const prependTransactionMessageInstruction = identity;
export const setTransactionMessageFeePayer = identity;
export const setTransactionMessageFeePayerSigner = identity;
export const setTransactionMessageLifetimeUsingBlockhash = identity;
export const SOLANA_ERROR__BLOCK_HEIGHT_EXCEEDED = 'SOLANA_ERROR__BLOCK_HEIGHT_EXCEEDED';
