export type BadgeType = 'new' | 'limited' | 'exclusive' | 'free' | 'sold-out';

export interface ShopItem {
  id: string;
  title: string;
  sub: string;
  desc: string;
  price: string;
  priceCents: number;
  image: string;
  category: string;
  badge?: BadgeType;
}

export const shopItems: ShopItem[] = [
  {
    id: 'orbiters-book',
    title: 'Orbiters of The Horizon',
    sub: 'By Jhinn Bay',
    desc: 'The official publication of the Ethereal Horizon. A spiritual commitment and a loving surrender to the small daily actions of orbiters that compounds into world peace.',
    price: '35 USDC',
    priceCents: 3500,
    image: '/images/orbits-book-cover.png',
    category: 'Stationery',
    badge: 'new',
  },
  {
    id: 'shirt',
    title: 'The Academy Shirt',
    sub: 'Official MWA Uniform',
    desc: 'Heavyweight cotton tee in midnight navy with the embroidered Academy crest on the chest. Boxy unisex cut, ribbed crew neck, runs true to size.',
    price: '42 USDC',
    priceCents: 4200,
    image: 'https://i.imgur.com/S3AMvJA.png',
    category: 'Uniforms',
    badge: 'exclusive',
  },
  {
    id: 'journal',
    title: 'Magazine 01',
    sub: 'Leather-bound, grid pages',
    desc: 'A 200-page leather field journal with dot-grid pages, gilded edges, and the Academy sigil debossed on the cover. Includes a ribbon bookmark and pen loop. Built for notes, reflections, and research sketches.',
    price: '45 USDC',
    priceCents: 4500,
    image: 'https://i.imgur.com/57ahVVX.png',
    category: 'Stationery',
    badge: 'new',
  },
  {
    id: 'hoodie',
    title: 'Cipher Hoodie',
    sub: 'Heavyweight 400gsm',
    desc: 'Oversized heavyweight hoodie in washed obsidian. Features a subtle glitch-pattern inner lining and "MENTAL WEALTH" debossed on the back yoke. Double-layered hood, kangaroo pocket with hidden zip.',
    price: '85 USDC',
    priceCents: 8500,
    image: 'https://i.imgur.com/TPujE2j.png',
    category: 'Uniforms',
    badge: 'sold-out',
  },
  {
    id: 'pin-set',
    title: 'Scholar Pin Set',
    sub: 'Enamel × Gold, Set of 5',
    desc: 'Five hard enamel pins representing the five disciplines: Cognition, Wealth, Health, Creativity, and Sovereignty. Each features micro-engraved serial numbers. Collect all five to unlock a hidden curriculum quest.',
    price: '28 USDC',
    priceCents: 2800,
    image: 'https://i.imgur.com/yUCxnDX.png',
    category: 'Accessories',
    badge: 'sold-out',
  },
  {
    id: 'lanyard',
    title: 'Scholar Lanyard',
    sub: 'Woven jacquard, breakaway clip',
    desc: 'Jacquard-woven lanyard with repeating Academy pattern. Breakaway safety clip and detachable badge holder. Required for campus access during intensive cohorts.',
    price: '14 USDC',
    priceCents: 1400,
    image: '/images/shop/scholar-lanyard.png',
    category: 'Accessories',
  },
  {
    id: 'notebook',
    title: 'Thesis Notebook',
    sub: 'A5, ruled, 120gsm paper',
    desc: 'Premium A5 notebook with ivory 120gsm ruled pages, lay-flat binding, and a cover embossed with the Academy\'s founding equation. For your most important ideas.',
    price: '16 USDC',
    priceCents: 1600,
    image: '/images/shop/thesis-notebook.png',
    category: 'Stationery',
  },
  {
    id: 'scholar-satchel',
    title: 'Scholar Satchel',
    sub: 'Weatherproof canvas & leather',
    desc: 'Structured messenger bag designed for text volumes, e-slates, and research gear. Features padded tablet compartment and magnetic brass latches.',
    price: '72 USDC',
    priceCents: 7200,
    image: '/images/shop/scholar-satchel.png',
    category: 'Accessories',
    badge: 'exclusive',
  },
  {
    id: 'fountain-pen',
    title: 'Quantum Brass Fountain Pen',
    sub: 'Precision 0.5mm nib',
    desc: 'Crafted from solid brushed brass with micro-etched discipline sigils. Features a precision nib tuned for rapid lecture notes and daily field note reflections.',
    price: '35 USDC',
    priceCents: 3500,
    image: '/images/shop/fountain-pen.png',
    category: 'Stationery',
    badge: 'new',
  },
  {
    id: 'scholar-slate',
    title: 'Scholar e-Paper Slate',
    sub: '10.3" glare-free digital notebook',
    desc: 'Paper-like e-ink display with zero lag for notes, textbooks, and guide research. Synchronizes automatically with your Academy curriculum notebook.',
    price: '195 USDC',
    priceCents: 19500,
    image: '/images/shop/scholar-slate.png',
    category: 'Tech',
    badge: 'limited',
  },
  {
    id: 'study-lamp',
    title: 'Spectral Focus Study Lamp',
    sub: 'Circadian spectrum LED',
    desc: 'Minimalist navy and gold study lamp engineered with circadian spectrum tuning to prevent eye fatigue during late-night research sessions.',
    price: '68 USDC',
    priceCents: 6800,
    image: '/images/shop/study-lamp.png',
    category: 'Tech',
  },
  {
    id: 'chronos-timer',
    title: 'Chronos Sand Timer',
    sub: '15-minute focus interval',
    desc: 'Hand-blown borosilicate glass filled with fine obsidian sand. Built for timing 15-minute daily field note sessions and deep focus sprints.',
    price: '24 USDC',
    priceCents: 2400,
    image: '/images/shop/chronos-timer.png',
    category: 'Stationery',
  },
  {
    id: 'desk-mat',
    title: 'Topology Grid Desk Mat',
    sub: '900×400mm micro-weave cloth',
    desc: 'Extra-large desk pad featuring the Academy\'s prerequisite DAG map printed in subtle cyan ink. Water-resistant surface with stitched edges.',
    price: '32 USDC',
    priceCents: 3200,
    image: '/images/shop/desk-mat.png',
    category: 'Accessories',
  },
  {
    id: 'card-vault',
    title: 'Titanium Card Vault',
    sub: 'RFID-blocking titanium',
    desc: 'Precision CNC-machined titanium card case for your scholar ID and keycards. Features a quick-slide thumb ejector and engraved Academy crest.',
    price: '40 USDC',
    priceCents: 4000,
    image: '/images/shop/card-vault.png',
    category: 'Tech',
  },
  {
    id: 'commencement-stole',
    title: 'Commencement Stole',
    sub: 'Silk weave with gold embroidery',
    desc: 'Archival navy silk stole worn during term milestones and research presentations. Features gold thread accents representing cohort achievements.',
    price: '48 USDC',
    priceCents: 4800,
    image: '/images/shop/commencement-stole.png',
    category: 'Uniforms',
    badge: 'exclusive',
  },
  {
    id: 'holographic-beaker',
    title: 'Resonance Crystal Beaker',
    sub: 'Iridescent borosilicate lab flask',
    desc: 'Handcrafted holographic glass flask that shifts color in ambient light. Used in the Academy chemistry & materials science cohorts.',
    price: '38 USDC',
    priceCents: 3800,
    image: '/images/shop/holographic-beaker.png',
    category: 'Tech',
    badge: 'new',
  },
  {
    id: 'prism-cube',
    title: 'Optical Dispersion Prism',
    sub: 'K9 crystal spectrum cube',
    desc: 'Solid optical glass cube designed for studying refraction and light wave physics. Projects sharp rainbow spectra across your study desk.',
    price: '26 USDC',
    priceCents: 2600,
    image: '/images/shop/prism-cube.png',
    category: 'Stationery',
  },
  {
    id: 'leather-tool-roll',
    title: 'Field Researcher Tool Roll',
    sub: 'Terracotta full-grain leather',
    desc: 'Rich warm cognac leather roll with slots for fountain pens, calipers, slide rules, and note refills. Hand-stitched with brass button studs.',
    price: '54 USDC',
    priceCents: 5400,
    image: '/images/shop/leather-tool-roll.png',
    category: 'Accessories',
    badge: 'exclusive',
  },
  {
    id: 'astrolabe',
    title: 'Brass Meridian Planisphere',
    sub: 'Engraved celestial computer',
    desc: 'Intricately laser-etched antique brass planisphere for mapping celestial coordinates, star positions, and navigational math.',
    price: '64 USDC',
    priceCents: 6400,
    image: '/images/shop/astrolabe.png',
    category: 'Stationery',
  },
  {
    id: 'botanical-press',
    title: 'Scholar Herbarium Press',
    sub: 'Solid oak & brass wingnuts',
    desc: 'Traditional wooden specimen press with heavy absorbent blotter cards for preserving field specimens and botanical observations.',
    price: '34 USDC',
    priceCents: 3400,
    image: '/images/shop/botanical-press.png',
    category: 'Stationery',
  },
  {
    id: 'sound-bowl',
    title: 'Frequency Resonance Bowl',
    sub: 'Hand-hammered 432Hz brass',
    desc: 'Tuned singing bowl crafted from seven-metal alloy. Used to mark the beginning and end of deep focus research blocks.',
    price: '46 USDC',
    priceCents: 4600,
    image: '/images/shop/sound-bowl.png',
    category: 'Accessories',
  },
  {
    id: 'mechanical-pencil',
    title: 'Draftsman Mechanical Pencil',
    sub: '0.5mm matte emerald aluminum',
    desc: 'Precision knurled aluminum mechanical pencil in deep forest emerald. Balanced weight distribution for geometric diagrams and technical drafting.',
    price: '28 USDC',
    priceCents: 2800,
    image: '/images/shop/mechanical-pencil.png',
    category: 'Stationery',
    badge: 'new',
  },
  {
    id: 'varsity-cardigan',
    title: 'Varsity Knit Cardigan',
    sub: 'Cream & burgundy wool blend',
    desc: 'Classic collegiate varsity cardigan in warm ivory with burgundy trim and Chenille Academy crest patch. Heavyweight rib knit.',
    price: '95 USDC',
    priceCents: 9500,
    image: '/images/shop/varsity-cardigan.png',
    category: 'Uniforms',
    badge: 'exclusive',
  },
  {
    id: 'levitating-globe',
    title: 'Levitating Orbital Globe',
    sub: 'Illuminated electromagnetic sphere',
    desc: 'Self-levitating orbital globe that floats and rotates above a matte slate base. Soft ambient halo lighting for desktop study.',
    price: '110 USDC',
    priceCents: 11000,
    image: '/images/shop/levitating-globe.png',
    category: 'Tech',
    badge: 'limited',
  },
  {
    id: 'scholar-bottle',
    title: 'Thermo Vacuum Flask',
    sub: 'Matte sage insulated steel',
    desc: 'Double-wall vacuum flask in matte sage green with laser-engraved Academy seal. Keeps drinks icy cold for 24 hours during long library sessions.',
    price: '32 USDC',
    priceCents: 3200,
    image: '/images/shop/scholar-bottle.png',
    category: 'Accessories',
  },
];

export function getShopItem(itemId: string): ShopItem | undefined {
  return shopItems.find((item) => item.id === itemId);
}

/**
 * Diamond prices for shop items, shared by the client (display + burn amount)
 * and the server (authoritative price for burn verification). The server never
 * trusts a client-supplied amount — it looks the price up here by item id.
 *
 * Diamonds are the fun, spendable currency: prices are set to feel affordable
 * to an engaged learner, not punishing. Paying with diamonds is a real burn
 * (a token sink), so it is offered as an alternative to the USDC price.
 */
export const SHOP_DIAMOND_PRICES: Record<string, number> = {
  'orbiters-book': 500,
  shirt: 650,
  journal: 700,
  hoodie: 1300,
  'pin-set': 450,
  lanyard: 200,
  notebook: 250,
  'scholar-satchel': 1100,
  'fountain-pen': 550,
  'scholar-slate': 2900,
  'study-lamp': 1050,
  'chronos-timer': 380,
  'desk-mat': 480,
  'card-vault': 620,
  'commencement-stole': 750,
  'holographic-beaker': 580,
  'prism-cube': 400,
  'leather-tool-roll': 820,
  astrolabe: 980,
  'botanical-press': 520,
  'sound-bowl': 700,
  'mechanical-pencil': 420,
  'varsity-cardigan': 1450,
  'levitating-globe': 1650,
  'scholar-bottle': 480,
};

export function getDiamondPrice(itemId: string): number | null {
  return SHOP_DIAMOND_PRICES[itemId] ?? null;
}
